Header
front-end-by-rimantas/35-grupe-portfolio-docland pull request #19
Opened 2022-04-12 17:19 UTC by Nuotaikos

2022-04-12 18:58 UTC, kauste reviewed
Rasyciau visible-lg, nes puslapyje nebesimato nav'o nuorodu kai ekrano plotis 991px;

2022-04-13 10:02 UTC, belauzas requested changes
Demo komentaras

2022-04-13 10:02 UTC, belauzas commented on index.html
> +                <nav class="hidden visible-md">
visible-lg

2022-04-13 10:03 UTC, belauzas commented on index.html
> +                <nav class="hidden visible-md">
Done

2022-04-13 11:05 UTC, Nuotaikos commented
> Rasyciau visible-lg, nes puslapyje nebesimato nav'o nuorodu kai ekrano plotis 991px;

@kauste , matosi. Su komanda pabandėme, matosi
![image](https://user-images.githubusercontent.com/101096500/163167275-23322a72-e781-4f5c-9f94-48680ffe2c33.png)

2022-04-13 11:06 UTC, Laurisdid approved these changes

2022-04-13 13:08 UTC, EgleNem approved these changes

2022-04-13 13:42 UTC, lukastabu approved these changes
atrodo gerai

2022-04-13 13:45 UTC, Nuotaikos commented
> Demo komentaras

Demo atsakymas:)

2022-04-13 13:52 UTC, enzofxx approved these changes

2022-04-13 14:28 UTC, kauste commented
taip, atliktoje matosi, bet pateiktoje uzduotyje nesimato:)

2022-04-13 18:58 UTC, kauste approved these changes

2022-04-14 07:39 UTC, merged