Pricing layout
front-end-by-rimantas/35-grupe-portfolio-docland pull request #37
Opened 2022-04-14 05:32 UTC by EgleNem

Fixed placement

2022-04-14 06:48 UTC, Nuotaikos submitted a review, later dismissed

2022-04-14 10:27 UTC, lukastabu approved these changes, later dismissed
atrodo gerai

2022-04-14 12:11 UTC, Laurisdid submitted a review, later dismissed

2022-04-14 12:15 UTC, Laurisdid submitted a review, later dismissed

2022-04-14 14:36 UTC, lukastabu requested changes
atrodo gerai

2022-04-14 14:36 UTC, lukastabu commented on index.html
> +            </div>
mano supratimu čia neužtenka palikti placeholderių, nes čia ne js elementai. turetų būti div su responsive pločiais ir strukturuotu turiniu, tokiu kaip kaina, unordered list ir list items (kur yra varnele (icon) ir monthly subscription, etc.)

2022-04-18 17:16 UTC, EgleNem commented
Pridėtas detalus price box tekstas

2022-04-18 23:40 UTC, kauste submitted a review, later dismissed

2022-04-19 08:46 UTC, kauste commented on index.html
> +    />
oj, favikono formatavima tik atstatyki:)

2022-04-19 11:03 UTC, kauste commented on index.html
> +    />
pataisyta

2022-04-19 11:06 UTC, lukastabu approved these changes

2022-04-19 11:07 UTC, kauste approved these changes

2022-04-19 11:07 UTC, merged