Syllabus
front-end-by-rimantas/35-grupe-portfolio-docland pull request #43
Opened 2022-04-14 13:54 UTC by Nuotaikos

2022-04-14 14:50 UTC, lukastabu requested changes

2022-04-14 14:50 UTC, lukastabu commented on index.html
> +    <!-- 3rd-party: FB -->
nelabai suprantu kam reikejo cia keisti, nes atsiras git konfliktai

2022-04-14 14:50 UTC, lukastabu commented on index.html
> +</html>
nereikejo keisti, nes bus git konfliktai. plius per standupa minejo kestutis, kad pabaigoj reikalinga tuscia eilute

2022-04-14 16:50 UTC, Nuotaikos commented on index.html
> +</html>
Done

2022-04-14 16:51 UTC, Nuotaikos commented on index.html
> +    <!-- 3rd-party: FB -->
Favicono neliečiau, kaip ir kitų  eilučių. Negaliu paaiškinti kodėl taip rodo

2022-04-18 16:14 UTC, EgleNem approved these changes

2022-04-19 10:30 UTC, kauste submitted a review, later dismissed

2022-04-19 11:09 UTC, lukastabu approved these changes

2022-04-19 11:25 UTC, Laurisdid submitted a review, later dismissed

2022-04-19 11:26 UTC, Laurisdid approved these changes

2022-04-19 11:33 UTC, kauste approved these changes

2022-04-19 11:33 UTC, merged