btn style
front-end-by-rimantas/35-grupe-portfolio-docland pull request #51
Opened 2022-04-19 13:50 UTC by EgleNem

Initial button style

2022-04-19 17:06 UTC, Nuotaikos requested changes
panašu, kad netyčia praleidai mygtuką ant heros kur video paleidžia

2022-04-19 19:02 UTC, kauste submitted a review, later dismissed
Kaip ir sakei, subscribe mygtukas nesustylinai, bet approvinu, jei nusprestumete merginti nesustylinta

2022-04-20 06:50 UTC, EgleNem commented
> panašu, kad netyčia praleidai mygtuką ant heros kur video paleidžia

Ačiū, pridėjau ;)

2022-04-20 11:29 UTC, kauste approved these changes

2022-04-20 11:30 UTC, Nuotaikos approved these changes

2022-04-20 11:30 UTC, merged